spring.config.import=optional:file:.env[.properties]

spring.application.name=datapi
server.port=8086

#mysql connection
spring.datasource.url=${LOCAL_DB_URL}
spring.datasource.username=${LOCAL_DB_USERNAME}
spring.datasource.password=${LOCAL_DB_PASSWORD}

#jpa/hibernate
spring.jpa.hibernate.ddl-auto=update